export const logo = document.querySelector('.logo');
export const logoCopy = document.querySelector('.logo-copy');
export const menuList = document.querySelector('.menu__list');
export const menuMainLinks = document.querySelectorAll('.menu__list-item');
export const menuPetsLinks = document.querySelectorAll('.menu__list-item-pets-page');
export const burgerMenuBtn = document.querySelector('.menu__burger-button');
export const menuOverlay = document.querySelector('.menu__overlay');
export const btnNotOnly = document.querySelector('.not-only__content-button');
export const btnOurFriends = document.querySelector('.our-friends__content-button');
export const header = document.querySelector('.header');
export const help = document.querySelector('.help');
export const footer = document.querySelector('.footer');
export const slider = document.querySelector('.our-friends__slider');
export const prevBtnSlider = document.querySelector('.our-friends__prev-button');
export const nextBtnSlider = document.querySelector('.our-friends__next-button');
export const popup = document.querySelector('.popup');
export const popupOverlay = document.querySelector('.popup__overlay');
export const popupBtn = document.querySelector('.popup__close-button');
export const popupContent = document.querySelector('.popup__content');
export const popupContentInner = document.querySelector('.popup__content-inner');
export const popupImage = document.createElement('img');
export const popupContainer = document.createElement('div');
export const popupPetName = document.createElement('div');
export const popupPetBreed = document.createElement('div');
export const popupPetDescription = document.createElement('div');
export const popupItems = document.createElement('div');
popupContentInner.appendChild(popupImage).classList.add('popup__content-image');
popupContentInner.appendChild(popupContainer).classList.add('popup__container');
popupContainer.appendChild(popupPetName).classList.add('popup__container-pet-name');
popupContainer.appendChild(popupPetBreed).classList.add('popup__container-pet-breed');
popupContainer.appendChild(popupPetDescription).classList.add('popup__container-pet-description');
popupContainer.appendChild(popupItems).classList.add('popup__container-items');